#!/bin/zsh

# Make SSH files executable
eval "$(ssh-agent -s)"
echo "Set files permissions..."
chmod 600 $HOME/.ssh/config
chmod 600 $HOME/.ssh/id_ed25519

echo "Test SSH connection..."
ssh -T git@github.com
if [ $? -le 1 ]
then
   echo "Cloning Settings/dotfiles repo..."
   git clone --bare git@github.com:webdev-skynet/osx-settings-dotfiles.git $HOME/.myconfig
fi

# Checkout
function cfg {
   /usr/bin/git --git-dir=$HOME/.myconfig/ --work-tree=$HOME $@
}

# Remove .ssh directory to prevent overwriting issues during the checkout
rm -rf .ssh 

echo "Checked out config.";
cfg checkout
cfg config status.showUntrackedFiles no
